#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run build:prod
npm run lint:ts
npm run lint:scss
npm run test:unit
#TODO Временно отключил, пока есть доступ к CI/CD
#npm run storybook:build
#npm run test:ui:ci
